/** @type {import('tailwindcss').Config} */

export default {
  content: ["./**/*.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        tablet: "640px",
        laptop: "1024px",
        desktop: "1280px",
      },
      maxWidth: {
        "8xl": "90rem",
        "9xl": "120rem",
      },
      background: {
        primary: "var(--neutral-White)",
        secondary: "var(--neutral-20)",
        brand: "var(--orange-10)",
      },
      colors: {
        gray: {
          0: "var(--gray-0)",
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
        },
        red: {
          0: "var(--red-0)",
          1: "var(--red-1)",
          2: "var(--red-2)",
          3: "var(--red-3)",
          4: "var(--red-4)",
          5: "var(--red-5)",
          6: "var(--red-6)",
          7: "var(--red-7)",
          8: "var(--red-8)",
          9: "var(--red-9)",
        },
        pink: {
          0: "var(--pink-0)",
          1: "var(--pink-1)",
          2: "var(--pink-2)",
          3: "var(--pink-3)",
          4: "var(--pink-4)",
          5: "var(--pink-5)",
          6: "var(--pink-6)",
          7: "var(--pink-7)",
          8: "var(--pink-8)",
          9: "var(--pink-9)",
        },
        grape: {
          0: "var(--grape-0)",
          1: "var(--grape-1)",
          2: "var(--grape-2)",
          3: "var(--grape-3)",
          4: "var(--grape-4)",
          5: "var(--grape-5)",
          6: "var(--grape-6)",
          7: "var(--grape-7)",
          8: "var(--grape-8)",
          9: "var(--grape-9)",
        },
        violet: {
          0: "var(--violet-0)",
          1: "var(--violet-1)",
          2: "var(--violet-2)",
          3: "var(--violet-3)",
          4: "var(--violet-4)",
          5: "var(--violet-5)",
          6: "var(--violet-6)",
          7: "var(--violet-7)",
          8: "var(--violet-8)",
          9: "var(--violet-9)",
        },
        indigo: {
          0: "var(--indigo-0)",
          1: "var(--indigo-1)",
          2: "var(--indigo-2)",
          3: "var(--indigo-3)",
          4: "var(--indigo-4)",
          5: "var(--indigo-5)",
          6: "var(--indigo-6)",
          7: "var(--indigo-7)",
          8: "var(--indigo-8)",
          9: "var(--indigo-9)",
        },
        blue: {
          0: "var(--blue-0)",
          1: "var(--blue-1)",
          2: "var(--blue-2)",
          3: "var(--blue-3)",
          4: "var(--blue-4)",
          5: "var(--blue-5)",
          6: "var(--blue-6)",
          7: "var(--blue-7)",
          8: "var(--blue-8)",
          9: "var(--blue-9)",
        },
        cyan: {
          0: "var(--cyan-0)",
          1: "var(--cyan-1)",
          2: "var(--cyan-2)",
          3: "var(--cyan-3)",
          4: "var(--cyan-4)",
          5: "var(--cyan-5)",
          6: "var(--cyan-6)",
          7: "var(--cyan-7)",
          8: "var(--cyan-8)",
          9: "var(--cyan-9)",
        },
        teal: {
          0: "var(--teal-0)",
          1: "var(--teal-1)",
          2: "var(--teal-2)",
          3: "var(--teal-3)",
          4: "var(--teal-4)",
          5: "var(--teal-5)",
          6: "var(--teal-6)",
          7: "var(--teal-7)",
          8: "var(--teal-8)",
          9: "var(--teal-9)",
        },
        green: {
          0: "var(--green-0)",
          1: "var(--green-1)",
          2: "var(--green-2)",
          3: "var(--green-3)",
          4: "var(--green-4)",
          5: "var(--green-5)",
          6: "var(--green-6)",
          7: "var(--green-7)",
          8: "var(--green-8)",
          9: "var(--green-9)",
        },
        lime: {
          0: "var(--lime-0)",
          1: "var(--lime-1)",
          2: "var(--lime-2)",
          3: "var(--lime-3)",
          4: "var(--lime-4)",
          5: "var(--lime-5)",
          6: "var(--lime-6)",
          7: "var(--lime-7)",
          8: "var(--lime-8)",
          9: "var(--lime-9)",
        },
        yellow: {
          0: "var(--yellow-0)",
          1: "var(--yellow-1)",
          2: "var(--yellow-2)",
          3: "var(--yellow-3)",
          4: "var(--yellow-4)",
          5: "var(--yellow-5)",
          6: "var(--yellow-6)",
          7: "var(--yellow-7)",
          8: "var(--yellow-8)",
          9: "var(--yellow-9)",
        },
        orange: {
          0: "var(--orange-0)",
          1: "var(--orange-1)",
          2: "var(--orange-2)",
          3: "var(--orange-3)",
          4: "var(--orange-4)",
          5: "var(--orange-5)",
          6: "var(--orange-6)",
          7: "var(--orange-7)",
          8: "var(--orange-8)",
          9: "var(--orange-9)",
        },
      },
      boxShadow: {
        xs: "0px 1px 2px 0px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.05)",
        sm: "0px 7px 7px -5px rgba(0, 0, 0, 0.04), 0px 10px 15px -5px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.05)",
        md: "0px 10px 10px -5px rgba(0, 0, 0, 0.04), 0px 20px 25px -5px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.05)",
        lg: "0px 12px 12px -7px rgba(0, 0, 0, 0.04), 0px 28px 23px -7px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.05)",
        xl: "0px 17px 17px -7px rgba(0, 0, 0, 0.04), 0px 36px 28px -7px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.05)",
      },
      fontSize: {
        //  Heading
        "40xl/700": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "32xl/700": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "24xl/700": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "20xl/700": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "18xl/700": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "16xl/700": ["16px", { lineHeight: "20px", fontWeight: "700" }],
        "12xl/700": ["12px", { lineHeight: "16px", fontWeight: "700" }],

        // Text bold
        "20md/600": ["20px", { lineHeight: "24px", fontWeight: "600" }],
        "18md/600": ["18px", { lineHeight: "20px", fontWeight: "600" }],
        "16md/600": ["16px", { lineHeight: "18px", fontWeight: "600" }],
        "14md/600": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "12md/600": ["12px", { lineHeight: "14px", fontWeight: "600" }],
        "10md/600": ["10px", { lineHeight: "12px", fontWeight: "600" }],

        // Text semi bold
        "20md/500": ["20px", { lineHeight: "24px", fontWeight: "500" }],
        "18md/500": ["18px", { lineHeight: "20px", fontWeight: "500" }],
        "16md/500": ["16px", { lineHeight: "18px", fontWeight: "500" }],
        "14md/500": ["14px", { lineHeight: "16px", fontWeight: "500" }],
        "12md/500": ["12px", { lineHeight: "14px", fontWeight: "500" }],

        // Text
        "20md/400": ["20px", { lineHeight: "24px", fontWeight: "400" }],
        "18md/400": ["18px", { lineHeight: "20px", fontWeight: "400" }],
        "16md/400": ["16px", { lineHeight: "18px", fontWeight: "400" }],
        "14md/400": ["14px", { lineHeight: "16px", fontWeight: "400" }],
        "12md/400": ["12px", { lineHeight: "14px", fontWeight: "400" }],
      },
      animation: {
        "pulse": "pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite;",
        "sound-wave-1": "soundWave 1.2s ease-in-out infinite",
        "sound-wave-2": "soundWave 1s ease-in-out infinite",
        "sound-wave-3": "soundWave 1.5s ease-in-out infinite",
        "sound-wave-4": "soundWave 0.8s ease-in-out infinite",
        "sound-wave-5": "soundWave 1.3s ease-in-out infinite",
      },
      keyframes: {
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        soundWave: {
          "0%, 100%": { height: "4px" },
          "50%": { height: "16px" },
        },
      },
    },
  },
  plugins: [],
}
