services:
  - type: web
    name: vcompass-schedule-ai
    runtime: python3
    region: singapore
    plan: starter
    rootDir: Schedule_AI
    buildCommand: |
      ls -la &&
      pip install --upgrade pip && 
      pip install -r requirements.txt &&
      echo "Checking JSON files:" &&
      ls -la *.json || echo "No JSON files found"
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    branch: main 